/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package desafio_9_graffi;

/**
 *
 * @author Usuario
 */
public class Desafio_9_Edad extends javax.swing.JPanel {

    /**
     * Creates new form Desafio_9_Edad
     */
    public Desafio_9_Edad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        btnValidar = new javax.swing.JButton();

        jLabel1.setText("Ingresa tu edad:");

        txtEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEdadActionPerformed(evt);
            }
        });

        btnValidar.setText("Validar edad");
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(btnValidar)))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnValidar)
                .addContainerGap(231, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
       // 1. Obtenemos el texto del JTextField
    String textoEdad = txtEdad.getText();
    
    try {
        // 2. Intentamos convertir el texto a un número entero
        int edad = Integer.parseInt(textoEdad);
        
        // 3. Si es un número, validamos la edad
        if (edad < 18) {
            // Error si es menor de edad
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Acceso denegado. Eres menor de edad.", 
                "Error de Edad", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        } else {
            // Bienvenida si es mayor de edad
            javax.swing.JOptionPane.showMessageDialog(this, 
                "¡Bienvenido! Acceso permitido.", 
                "Acceso Concedido", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
        
    } catch (NumberFormatException e) {
        // 4. Si falla la conversión (ej. "hola"), capturamos la excepción
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error: Debes ingresar solo números.", 
            "Error de Formato", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    
    // Limpiar el campo de texto después de validar
    txtEdad.setText("");
    }//GEN-LAST:event_btnValidarActionPerformed

    private void txtEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEdadActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnValidar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtEdad;
    // End of variables declaration//GEN-END:variables
}
