/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package desafio_9_graffi;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class Desafio_9_Lenguajes extends javax.swing.JPanel {

    /**
     * Creates new form Desafio_9_Lenguajes
     */
    public Desafio_9_Lenguajes() {
        initComponents();
        
        // 2. Añadir el listener de mouse a la JList
    lstLenguajes.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            
            // 3. Comprobar si fue un doble clic
            if (evt.getClickCount() == 2) {
                
                // 4. Obtener el lenguaje seleccionado
                String lenguaje = (String) lstLenguajes.getSelectedValue();
                
                // 5. Preparar el mensaje
                String mensaje = "";
                switch (lenguaje) {
                    case "Java":
                        mensaje = "Java: Orientado a objetos, robusto y muy popular en el mundo empresarial (backend).";
                        break;
                    case "Python":
                        mensaje = "Python: Fácil de aprender, ideal para ciencia de datos, IA y desarrollo web.";
                        break;
                    case "C++":
                        mensaje = "C++: Muy potente y rápido, usado para videojuegos, sistemas operativos y software de alto rendimiento.";
                        break;
                    case "JavaScript":
                        mensaje = "JavaScript: El lenguaje principal del desarrollo web (frontend y backend con Node.js).";
                        break;
                    case "Ruby":
                        mensaje = "Ruby: Conocido por su framework 'Ruby on Rails', enfocado en la productividad y felicidad del desarrollador.";
                        break;
                    case "Swift":
                        mensaje = "Swift: El lenguaje moderno de Apple para crear aplicaciones para iOS, macOS y más.";
                        break;
                    default:
                        mensaje = "Lenguaje no reconocido.";
                }
                
                // 6. Mostrar el mensaje
                javax.swing.JOptionPane.showMessageDialog(null, mensaje, "Info: " + lenguaje, JOptionPane.INFORMATION_MESSAGE);
            }
        }
    });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lstLenguajes = new javax.swing.JList<>();

        lstLenguajes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Java", "Python", "C++", "JavaScript", "Ruby", "Swift" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstLenguajes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstLenguajes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(185, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> lstLenguajes;
    // End of variables declaration//GEN-END:variables
}
