/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package desafio_9_graffi;

/**
 *
 * @author Usuario
 */
public class Desafio_9_Fuente extends javax.swing.JPanel {

    /**
     * Creates new form Desafio_9_Fuente
     */
    public Desafio_9_Fuente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbTamanos = new javax.swing.JComboBox<>();
        lblEjemplo = new javax.swing.JLabel();

        cmbTamanos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "12", "14", "16", "18", "20" }));
        cmbTamanos.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTamanosItemStateChanged(evt);
            }
        });

        lblEjemplo.setText("Texto de ejemplo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmbTamanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEjemplo)
                .addContainerGap(219, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbTamanos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEjemplo))
                .addContainerGap(272, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTamanosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTamanosItemStateChanged
        // Verificamos que el evento sea de un ítem que ha sido SELECCIONADO
    if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
        
        // 1. Obtenemos el tamaño seleccionado (viene como un String)
        String tamanoSeleccionado = (String) cmbTamanos.getSelectedItem();
        
        // 2. Lo convertimos a un número (entero)
        int tamanoInt = Integer.parseInt(tamanoSeleccionado);
        
        // 3. Obtenemos la fuente actual del label (para no perder el tipo de letra, negrita, etc.)
        java.awt.Font fuenteActual = lblEjemplo.getFont();
        
        // 4. Creamos una fuente nueva, usando las propiedades de la fuente actual pero con el NUEVO tamaño
        java.awt.Font nuevaFuente = new java.awt.Font(
            fuenteActual.getName(),  // Mantiene el mismo tipo de letra (ej. "Tahoma")
            fuenteActual.getStyle(), // Mantiene el mismo estilo (ej. PLAIN, BOLD)
            tamanoInt                // Aplica el nuevo tamaño
        );
        
        // 5. Aplicamos la nueva fuente al label
        lblEjemplo.setFont(nuevaFuente);
    }
    }//GEN-LAST:event_cmbTamanosItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbTamanos;
    private javax.swing.JLabel lblEjemplo;
    // End of variables declaration//GEN-END:variables
}
